Bump org.springframework.boot:spring-boot-dependencies from 2.7.17 to 2.7.18 (#268)
Bumps
[org.springframework.boot:spring-boot-dependencies](https://github.com/spring-projects/spring-boot)
from 2.7.17 to 2.7.18.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/spring-projects/spring-boot/releases">org.springframework.boot:spring-boot-dependencies's
releases</a>.</em></p>
<blockquote>
<h2>v2.7.18</h2>
<h2>⚠️ Noteworthy Changes</h2>
<ul>
<li>Following the Paketo team's <a
href="https://blog.paketo.io/posts/paketo-bionic-builder-is-unsafe/">announcement</a>
that the Bionic CNB builders will be removed, the default builder using
by <code>bootBuildImage</code> (Gradle) and
<code>spring-boot:build-image</code> (Maven) has been changed to Paketo
Jammy <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38477">#38477</a></li>
</ul>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li>App fails to start with a NoSuchMethodError when using Flyway 10.0.0
<a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38164">#38164</a></li>
<li>spring.webflux.multipart.max-disk-usage-per-part behaves incorrectly
for values where the number of bytes overflows an int <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38146">#38146</a></li>
<li>Mail health indicator fails when host is not set in properties <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38007">#38007</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Document supported SQL comment prefixes <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/38385">#38385</a></li>
<li>Fix link to Elasticsearch health indicator <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/38330">#38330</a></li>
<li>Improve --help and documentation for &quot;encodepassword
-a/--algorithm&quot; in the Spring Boot CLI <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38203">#38203</a></li>
<li>Document that TomcatConnectorCustomizers are not applied to
additional connectors <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38183">#38183</a></li>
<li>MyErrorWebExceptionHandler example in documentation isn't working <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38104">#38104</a></li>
<li>Document that SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS is
disabled by default <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38083">#38083</a></li>
<li>Update &quot;Running Behind a Front-end Proxy Server&quot; to
include reactive and ForwardedHeaderTransformer <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/37282">#37282</a></li>
<li>Improve documentation of <code>classpath.idx</code> file and its
generation by the Maven and Gradle plugins <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/37125">#37125</a></li>
<li>Document configuration for building images with Colima <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34522">#34522</a></li>
<li>Code sample in &quot;Developing Your First Spring Boot
Application&quot; does not work <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34513">#34513</a></li>
<li>Document ConfigurationPropertyCaching <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34172">#34172</a></li>
<li>Document that application.* banner variables require a packaged jar
or the use of Boot's launcher <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/33489">#33489</a></li>
<li>Add section on AspectJ support <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/32642">#32642</a></li>
<li>Document server.servlet.encoding.* properties and
server.servlet.encoding.mapping in particular <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/32472">#32472</a></li>
<li>Add a section on customizing embedded reactive servers <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/31917">#31917</a></li>
<li>Clarify that MVC components provided through WebMvcRegistrations are
subject to subsequent processing and configuration by MVC <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/31232">#31232</a></li>
<li>Clarifying documentation on including a top-level
<code>@TestConfiguration</code> class in a test <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/30513">#30513</a></li>
<li>Clarify that <code>@AutoConfigureWebTestClient</code> binds
WebTestClient to mock infrastructure <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/29890">#29890</a></li>
<li>Improve systemd configuration documentation <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/28453">#28453</a></li>
<li>Document how to customize the basePackages that auto-configurations
consider (for example Spring Data Repositories) <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/27549">#27549</a></li>
<li>Document additional user configuration that's required after setting
<code>spring.hateoas.use-hal-as-default-json-media-type</code> to
<code>false</code> <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/26814">#26814</a></li>
<li>Add how-to documentation for test-only database migrations with
Flyway/Liquibase <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/26796">#26796</a></li>
</ul>
<h2>:hammer: Dependency Upgrades</h2>
<ul>
<li>Upgrade to ActiveMQ 5.16.7 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38427">#38427</a></li>
<li>Upgrade to DB2 JDBC 11.5.9.0 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38428">#38428</a></li>
<li>Upgrade to Dropwizard Metrics 4.2.22 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38429">#38429</a></li>
<li>Upgrade to Elasticsearch 7.17.15 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38430">#38430</a></li>
<li>Upgrade to Glassfish JAXB 2.3.9 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38431">#38431</a></li>
<li>Upgrade to Micrometer 1.9.17 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38279">#38279</a></li>
<li>Upgrade to Netty 4.1.101.Final <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38432">#38432</a></li>
<li>Upgrade to Pooled JMS 1.2.6 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38433">#38433</a></li>
<li>Upgrade to Reactor Bom 2020.0.38 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38280">#38280</a></li>
<li>Upgrade to Spring Batch 4.3.10 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38281">#38281</a></li>
<li>Upgrade to Spring Data Bom 2021.2.18 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38282">#38282</a></li>
<li>Upgrade to Spring Framework 5.3.31 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38283">#38283</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/0c8b382d42db22b92efcf47000d0ff9ef4971629"><code>0c8b382</code></a>
Release v2.7.18</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/5490e73922b37a7f0bdde43eb318cb1038b45d60"><code>5490e73</code></a>
Improve Tags generation for methods names</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/7ad6e4470c945ae0e39e63af28c47aebbe27bbc0"><code>7ad6e44</code></a>
Upgrade to Spring Batch 4.3.10</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/a6346fba08f78f01737d192be1b4221e8c365684"><code>a6346fb</code></a>
Merge pull request <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38385">#38385</a>
from PENEKhun</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/0171ed205cba038e0b8462228df3448cbc81c518"><code>0171ed2</code></a>
Polish &quot;Document comments in SQL for database
initialization&quot;</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/578d0436e07b5fc7076e2eb22f2e3176abaf4f0a"><code>578d043</code></a>
Document comments in SQL for database initialization</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/49c4f33919261a63c2b5eed1fd80fea0aed4b36f"><code>49c4f33</code></a>
Prepare for the final OSS release of 2.7.x</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/b473ffdea2b53a1fc7ee46f0b6c304f03333d3ed"><code>b473ffd</code></a>
Upgrade to Spring Integration 5.5.20</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/d1cce0f8ef705b1989f36484c3d9f337b5e1449f"><code>d1cce0f</code></a>
Upgrade default CNB builders to Paketo Jammy</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/95fbb49a08dcdf49ca748cceafb1c98494e0b225"><code>95fbb49</code></a>
Upgrade to Tomcat 9.0.83</li>
<li>Additional commits viewable in <a
href="https://github.com/spring-projects/spring-boot/compare/v2.7.17...v2.7.18">compare
view</a></li>
</ul>
</details>
<br />

<details>
<summary>Most Recent Ignore Conditions Applied to This Pull
Request</summary>

| Dependency Name | Ignore Conditions |
| --- | --- |
| org.springframework.boot:spring-boot-dependencies | [>= 3.a, < 4] |
</details>


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.springframework.boot:spring-boot-dependencies&package-manager=maven&previous-version=2.7.17&new-version=2.7.18)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>