Bump org.projectlombok:lombok from 1.18.30 to 1.18.34 (#310)
Bumps
[org.projectlombok:lombok](https://github.com/projectlombok/lombok) from
1.18.30 to 1.18.34.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/projectlombok/lombok/blob/master/doc/changelog.markdown">org.projectlombok:lombok's
changelog</a>.</em></p>
<blockquote>
<h3>v1.18.34 (June 28th, 2024)</h3>
<ul>
<li>PLATFORM: Added support for Eclipse 2024-06; you'd get some
<code>NoSuchMethodError</code> traces in your logs if using
<code>@Builder</code> or <code>@Singular</code> prior to this fix.
[Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3638">#3638</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3638">projectlombok/lombok#3638</a>).</li>
<li>IMPROBABLE BREAKING CHANGE: Lombok now adds
<code>@lombok.Generated</code> by default to methods and types it
generates. This may result in accidentally increasing your test coverage
percentage. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3667">#3667</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3667">projectlombok/lombok#3667</a>).</li>
<li>IMPROBABLE BREAKING CHANGE: When <code>lombok.config</code> contains
<code>lombok.onX.flagUsage = WARNING</code>, from now on warnings will
actually be generated if onX is used.[Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/2848">#2848</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/2848">projectlombok/lombok#2848</a>)</li>
<li>BUGFIX: When <code>@SuperBuilder</code> was used on a type with an
generic array type, it would error <code>wrong number of type
arguments</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3694">#3694</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3694">projectlombok/lombok#3694</a>).</li>
<li>FEATURE: Lombok generates javadoc for you for most of the methods it
adds; with this release, javadoc is also added to generated
constructors. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/933">#933</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/933">projectlombok/lombok#933</a>).</li>
</ul>
<h3>v1.18.32 (March 20th, 2024)</h3>
<ul>
<li>PLATFORM: Initial JDK22 support added.</li>
<li>PLAFTORM Added support for Eclipse 2024-03. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3620">#3620</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3620">projectlombok/lombok#3620</a>).</li>
<li>PLATFORM: Added support for recent versions of eclipse (released Q4
2023 or later or so) which would cause failures in the eclipse logs such
as <code>java.lang.NoSuchMethodError: 'java.lang.StringBuffer
org.eclipse.jdt…</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3564">#3564</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3564">projectlombok/lombok#3564</a>).</li>
<li>FEATURE: <code>@Locked</code> has been introduced. Like
<code>@Synchronized</code> but with
<code>java.util.concurrent.locks</code> locks instead of the
<code>synchronized</code> primitive. Thanks, Pim van der Loos for the
PR! [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3506">#3506</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3506">projectlombok/lombok#3506</a>).</li>
<li>NECROMANCY: Inlining a generated getter in eclipse would result in
eclipse incorrectly replacing calls with <code>@Getter</code> instead of
the actual field's name. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/562">#562</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/562">projectlombok/lombok#562</a>).
This issue is almost old enough to drink. Points for dedication go to
Rawi for fixing this one.</li>
<li>BUGFIX: When <code>@SuperBuilder</code> was used on a type with an
annotated generic type, it would error <code>wrong number of type
arguments</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3592">#3592</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3592">projectlombok/lombok#3592</a>).</li>
<li>BUGFIX: It was possible to create an infinite build loop using
<code>@ExtensionMethod</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3225">#3225</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3225">projectlombok/lombok#3225</a>).</li>
<li>BUGFIX: Using <code>@Getter(lazy=true)</code> would fail if the
expression contained a variable called <code>value</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/2917">#2917</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/2917">projectlombok/lombok#2917</a>).</li>
<li>BUGFIX: Many lombok features wouldn't work properly on records
contained within an outer type unless you explicitly marked it
<code>static</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3497">#3497</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3497">projectlombok/lombok#3497</a>)
[Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3559">#3559</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3559">projectlombok/lombok#3559</a>).</li>
<li>BUGFIX: Eclipse projects using the
<code>com.pro-crafting.tools:jasperreports-plugin</code> will now
compile.</li>
<li>BUGFIX: <code>@FieldNameConstants</code> now works when generated
fields are involved. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3529">#3529</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3529">projectlombok/lombok#3529</a>).</li>
<li>IMPROBABLE BREAKING CHANGE: For JSpecify, the package name changed
from <code>org.jspecify.nullness</code> to
<code>org.jspecify.annotations</code>, which might lead to a different
null analysis. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3608">#3608</a>](<a
href="https://redirect.github.com/projectlombok/lombok/pull/3608">projectlombok/lombok#3608</a>).</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/projectlombok/lombok/commit/fbbe7f07c817df5e8b7079b64a023749dcff2127"><code>fbbe7f0</code></a>
[release] pre-release version bump</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/3cd41e8fa00adafac52a401f50ef6628f4153258"><code>3cd41e8</code></a>
[trivial] some test cases were failing (due to the constructor-javadoc
update...</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/1384244b1331c3e078af2ab8ea3bbc71bcb5de1d"><code>1384244</code></a>
Merge pull request <a
href="https://redirect.github.com/projectlombok/lombok/issues/3698">#3698</a>
from stevebosman/fix-sneaky-throws-doc</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/d90ec73e571ceb958c28e9925d0e9d8057fa5ba9"><code>d90ec73</code></a>
[trivial] [style]</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/3b68e39d1003125d9b152542df0b4d87abba51dc"><code>3b68e39</code></a>
Merge pull request <a
href="https://redirect.github.com/projectlombok/lombok/issues/3697">#3697</a>
from janrieke/superbuilder-fix-array-type-param</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/fdafa9a0a69009d508578287e53d9cb57edc5deb"><code>fdafa9a</code></a>
Merge pull request <a
href="https://redirect.github.com/projectlombok/lombok/issues/3690">#3690</a>
from Rawi01/eclipse_2024_06</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/78c1f471763d9434a8e25b58bccfaf390e59a195"><code>78c1f47</code></a>
Merge pull request <a
href="https://redirect.github.com/projectlombok/lombok/issues/3689">#3689</a>
from Rawi01/nested-javadoc</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/da815a66d1d18f50a318dda3c7db0e283313e436"><code>da815a6</code></a>
Merge pull request <a
href="https://redirect.github.com/projectlombok/lombok/issues/3674">#3674</a>
from Rawi01/standardexception-fields</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/c61a404b410bd482fcd6a48d303fb483932214d0"><code>c61a404</code></a>
[trivial]</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/6cf6caf468710fbcbb11165ad0bc2548aa8f84e3"><code>6cf6caf</code></a>
Merge pull request <a
href="https://redirect.github.com/projectlombok/lombok/issues/3673">#3673</a>
from Rawi01/eclipse_field_generated</li>
<li>Additional commits viewable in <a
href="https://github.com/projectlombok/lombok/compare/v1.18.30...v1.18.34">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.projectlombok:lombok&package-manager=maven&previous-version=1.18.30&new-version=1.18.34)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>